### ISSUE TITLE
Internal Reference is backwards

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#2]
I have just added a new customer and the Internal Reference was generated as 

Internal Reference | 179XNY

The internal reference should start with the letters first and then the number like XNY179. This needs to be fixed.

**Comment by mdi-odoo** [comment]
Fixed in the commit: https://github.com/StrategicDimensions/inuka/commit/a72292e1b98bf8ee234c2227cc6057f0ed05c655 .
