### ISSUE TITLE
Cannot Create a New User

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#23]
When you try to create a new user, we are getting an error: 
- Mobile should be unique
- If you use the same email address for the user, you get the error Email must be unique
- The name of the user is also changing to the internal reference of the associated partner record when you add a user.

**Comment by DanielMaimba** [comment]
We are also getting Mobile should be 11 digits error when trying to create a new user. This should not apply when creating users.

**Comment by mdi-odoo** [comment]
It's already fixed.
