### ISSUE TITLE
Internal Server Error on eCommerce

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#35]
We are experiencing a number of internal server errors, in these instances:

Scenario 1
- Go to the website shop without logging on (https://inuka-master-staging-9245.dev.odoo.com)
- Select product to purchase
- on shopping cart, choose login so you can login (dmaimba@yahoo.com/test123)
- when you enter the login details it gives an internal server error.

Scenario 2
- login to website (https://inuka-master-staging-9245.dev.odoo.com) as (dmaimba@yahoo.com/test123)
- go to shop and select products, and go through shopping cart
- choose mygate as payment method
- when payment is successful and it returning to odoo, you get an internal server error. Its trying to get back to this link: https://inuka-master-staging-9245.dev.odoo.com/payment/mygate/return

**Comment by mdi-odoo** [comment]
It's already fixed.
