### ISSUE TITLE
POS: PV Points showing currency when printing invoice

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#38]
When the invoice is printed on the pos, the Currency Symbol is being printed on the Total PV points and is should not print. Please remove the currency symbol.

<img width="769" alt="screen shot 2017-12-19 at 09 42 05" src="https://user-images.githubusercontent.com/14073662/34146236-dcfab0c6-e4a1-11e7-80dc-e0738867bee2.png">

**Comment by mdi-odoo** [comment]
Fixed at revision: https://github.com/StrategicDimensions/inuka/commit/342c4f308944fe4c8917f3d650a699729627a530
