### ISSUE TITLE
Cash Allocation Process: Matching of Statement Lines with Partner and account

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#40]
When the matching process runs and matches the partner to a statement line, it is also matching the Accounts receivable account but it is matching to the accounts receivable account which does not belong to the company that owns the bank.

In my test, the bank account belongs to Company = INUKA but it mapped to the accounts receivable account which belongs to Company = INUKA Namibia.

If the bank account belongs to INUKA the account receivable account selected should also be the one for INUKA.

**Comment by mdi-odoo** [comment]
Fixed at revision: https://github.com/StrategicDimensions/inuka/commit/d2e263a408039b25b114ad96b799698222197db5
