### ISSUE TITLE
Cash Allocation Process: Final Bank Statement matching with Partner

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#41]
When you import the Final Bank Statement, there should be a match run to associate the final bank statement line with the bank statement line. 

A test done found that the matching is not happening.

If the match is found, the reconciliation should also be automatic and not rely on it being done manually

**Comment by mdi-odoo** [comment]
Fixed at revision: https://github.com/StrategicDimensions/inuka/commit/8b91885cc63c52dcd5f5117e98dd55785ce91db5
