### ISSUE TITLE
Watchlist: Add Watchlist, Remove Watchlist buttons Incorrect

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#42]
![image](https://user-images.githubusercontent.com/14073662/34812348-fff9f046-f6ad-11e7-95be-dd2456146c29.png)

Please change the buttons for the Add Watchlist & Remove Watchlist to be a Green button above the form as per the image.

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/20564e902664cffa2640caf4eed463858c64cdbf .
