### ISSUE TITLE
Partner From: Make Status field a Status Bar Widget

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#43]
![image](https://user-images.githubusercontent.com/14073662/34812494-75c2bea2-f6ae-11e7-9e69-60c0fa69e844.png)
Please make the Status field into Status Bar Widget so that it shows on the top right of the form. But due to the number of statuses, we want to display two other statuses after the current status of the customer. So if the customers status is New, then the status bar should show the following 
New > Junior > Senior
When this member status changes to Senior then the status bar should show
Senior > Pearl > Ruby

This means that is should only show 3 statuses at a time.

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/76910f18f52e7682d78f731b85a9104107dd13e1 .
