### ISSUE TITLE
Pricelist Changing when status = Candidate

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#46]
If you edit a member where the status = candidate, the pricelist gets updated to Established Pricelist which should not happen when the status is candidate or new. If you edit a record where status = candidate it should not trigger the update of the pricelist.

<img width="982" alt="screen shot 2018-01-23 at 04 30 46" src="https://user-images.githubusercontent.com/14073662/35255196-8bf2a24a-fff6-11e7-8372-1f93a8cf6ba9.png">

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/981d95be7da991a2b8911808074ad24c8a923804 .
