### ISSUE TITLE
Updating Order Total and PV fields when order is confirmed not Working

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#48]
When the Confirm Order button is clicked, the following fields should be updated automatically by the system:
<img width="531" alt="screen shot 2018-01-23 at 10 29 59" src="https://user-images.githubusercontent.com/14073662/35265301-68679a4c-0028-11e8-812b-67fbfe10c58e.png">

This is currently not working

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/cab937de8f4b6b3f355be59d4a3784e73579e5dd .
