### ISSUE TITLE
Connection Lost when you run (Calculate MTD) cron manually

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#50]
We getting connection lost when you run the Calculate MTD cron manually. 

It also does not update the MTD fields.
![image](https://user-images.githubusercontent.com/14073662/35385858-76d7646c-01d2-11e8-8469-23a853335e2f.png)

**Comment by mdi-odoo** [comment]
Its takes too long time to calculate MTD, May be due to that cron job is killed before process is completed and every changes are rollbacked.
