### ISSUE TITLE
URGENT: Cannot Create a new member (Mobile should be unique)

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#55]
Everytime you try to create a new customer, Odoo gives the error 'Mobile should be unique' even though the mobile number does not exist on the system. You can add the number like 2777777777777777777 and it still gives the same error.

Please review urgently.

**Comment by mdi-odoo** [comment]
Fixed in revision : https://github.com/StrategicDimensions/inuka/commit/df68d6dc10fe30823944a45a194dba709904d81f .
