### ISSUE TITLE
Urgent: New char field Portal Password

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#56]
Please add a new chat field called ‘Portal Password’ on res.partner which should only apply for is_customer = TRUE

this field should be added to the Device info Tab on the customer record and should be read only. It should only be updated via the api or an import.

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/114e68380ba452ae38501641c2367c027846599a .
