### ISSUE TITLE
Error while validating constraint  object of type 'int' has no len() - When creating new customer

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#57]
When you try to create a new customer and click save, the system then throws the following error:

<img width="668" alt="screen shot 2018-02-06 at 21 33 01" src="https://user-images.githubusercontent.com/14073662/35880101-a4a4aafa-0b85-11e8-8077-86c9f4b8f101.png">

**Comment by mdi-odoo** [comment]
Fixed in revision:  https://github.com/StrategicDimensions/inuka/commit/56e141c72634892c9eee14376a77dd3f50907bef .
