### ISSUE TITLE
Sales Upload Error: (Error: not all arguments converted during string formatting)

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#58]
When you create a sales upload record and select the file and click on the Start Button, the record is giving an error (Error: not all arguments converted during string formatting) and showing it in the result field. See below:

<img width="1076" alt="screen shot 2018-02-07 at 10 05 03" src="https://user-images.githubusercontent.com/14073662/35905133-99d8ea64-0bee-11e8-8969-21f3522434a1.png">

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/a9714f38e6c6a33a64a5e0d8e4b4af7aa3ab7fd0 .
