### ISSUE TITLE
Status Change Tickets should have a stage of 'New'

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#60]
When a ticket is created for a status change the status is not populated, the stage should be populated as 'New'

<img width="852" alt="screen shot 2018-02-08 at 06 19 17" src="https://user-images.githubusercontent.com/14073662/35958800-6081843e-0cab-11e8-8d7d-ccc4d7d8ca19.png">

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/a6559cd192b07dc7fa499e51c1429eb2fdfefc47 .
