### ISSUE TITLE
Automated Actions should not action when you create a vendor

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#61]
When you create a new vendor (is a vendor = TRUE) the system is running the automated action which sets the Price List and Status.

Please can you update this automated action so that it only updates records that are (is a customer = TRUE)

![image](https://user-images.githubusercontent.com/14073662/35961498-8f1ca8ae-0cb6-11e8-8641-c7d19a7a3d40.png)

**Comment by mdi-odoo** [comment]
I have checked the code, I don't found any issue with code. Its just log a note when status & pricelist is changed, no automation actions is triggered  .

**Comment by DanielMaimba** [comment]
@mdi-odoo but why is the status changing when you add the Vendor, the status field is not even available to select for a vendor. Is the status field defaulting to candidate for all partners??

**Comment by mdi-odoo** [comment]
Yes, status field defaulting to candidate for all partners.

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/ca95a5c5d07462d93ca6c539dce92b49b43e1ba1 .
