### ISSUE TITLE
Address & Mobile fields should not be Required for Vendors

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#62]
The Address fields and the Mobile field should not be mandatory for (is a vendor = TRUE) they should only be mandatory when (is a customer = TRUE)

![image](https://user-images.githubusercontent.com/14073662/35962967-f075cb1c-0cbb-11e8-984d-d08f7ed7bcac.png)

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/f9703d1b3b7a9be80ef8bfcfa8fdc19384b49680 .
