### ISSUE TITLE
Email required when creating new customer: Creating Portal User

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#63]
When you create a new customer the system will automatically create a new portal user also however the system is trying to send a portal confirmation email to the new customer/member. But if the new customer created does not have an email address it is giving the following error.
<img width="375" alt="screen shot 2018-02-12 at 09 05 33" src="https://user-images.githubusercontent.com/14073662/36086683-6fb4c79e-0fd6-11e8-8428-eb822cc3b8b9.png">

Please update the code so that it only sends the email if there is an email address entered for that customer. If there is no email address it should not send and it should not show the error.

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/b9429b6e307a1432665cf47de8455d6de20d4113 .
