### ISSUE TITLE
Purchase Automation sending multiple emails (Procure2Pay)

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#8]
When a purchase order goes to the approve stage, there are multiple approval emails being sent instead of one. If you then log a note or make any change on the order it will sent the approval emails again. This should not be the case.

The email notification should only be sent once when the purchase order first goes into the To Approve status.
<img width="1029" alt="screen shot 2017-11-08 at 15 28 21" src="https://user-images.githubusercontent.com/14073662/32552194-c3666676-c49b-11e7-9fbf-4e726e6c8130.png">

**Comment by mdi-odoo** [comment]
Fixed in the commit: https://github.com/StrategicDimensions/inuka/commit/b6ef362aa9cb37ff604f0c8d09cc6427784008b1 .
